//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusServicesClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Passenger", Namespace="http://schemas.datacontract.org/2004/07/BusServices")]
    [System.SerializableAttribute()]
    public partial class Passenger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime JourneyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeatNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime JourneyDate {
            get {
                return this.JourneyDateField;
            }
            set {
                if ((this.JourneyDateField.Equals(value) != true)) {
                    this.JourneyDateField = value;
                    this.RaisePropertyChanged("JourneyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatNumber {
            get {
                return this.SeatNumberField;
            }
            set {
                if ((this.SeatNumberField.Equals(value) != true)) {
                    this.SeatNumberField = value;
                    this.RaisePropertyChanged("SeatNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPassengerService1")]
    public interface IPassengerService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/GetData", ReplyAction="http://tempuri.org/IPassengerService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/GetData", ReplyAction="http://tempuri.org/IPassengerService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/InsertPassengerDetails", ReplyAction="http://tempuri.org/IPassengerService1/InsertPassengerDetailsResponse")]
        string InsertPassengerDetails(BusServicesClient.ServiceReference1.Passenger passeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/InsertPassengerDetails", ReplyAction="http://tempuri.org/IPassengerService1/InsertPassengerDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertPassengerDetailsAsync(BusServicesClient.ServiceReference1.Passenger passeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/GetAllPassengerDetails", ReplyAction="http://tempuri.org/IPassengerService1/GetAllPassengerDetailsResponse")]
        System.Data.DataSet GetAllPassengerDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/GetAllPassengerDetails", ReplyAction="http://tempuri.org/IPassengerService1/GetAllPassengerDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllPassengerDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/DeletePassengerDetails", ReplyAction="http://tempuri.org/IPassengerService1/DeletePassengerDetailsResponse")]
        bool DeletePassengerDetails(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/DeletePassengerDetails", ReplyAction="http://tempuri.org/IPassengerService1/DeletePassengerDetailsResponse")]
        System.Threading.Tasks.Task<bool> DeletePassengerDetailsAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/UpdatePassengerDetails", ReplyAction="http://tempuri.org/IPassengerService1/UpdatePassengerDetailsResponse")]
        string UpdatePassengerDetails(BusServicesClient.ServiceReference1.Passenger passInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/UpdatePassengerDetails", ReplyAction="http://tempuri.org/IPassengerService1/UpdatePassengerDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdatePassengerDetailsAsync(BusServicesClient.ServiceReference1.Passenger passInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/GetPassengerByName", ReplyAction="http://tempuri.org/IPassengerService1/GetPassengerByNameResponse")]
        System.Data.DataSet GetPassengerByName(string passInfoName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPassengerService1/GetPassengerByName", ReplyAction="http://tempuri.org/IPassengerService1/GetPassengerByNameResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPassengerByNameAsync(string passInfoName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPassengerService1Channel : BusServicesClient.ServiceReference1.IPassengerService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PassengerService1Client : System.ServiceModel.ClientBase<BusServicesClient.ServiceReference1.IPassengerService1>, BusServicesClient.ServiceReference1.IPassengerService1 {
        
        public PassengerService1Client() {
        }
        
        public PassengerService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PassengerService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassengerService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PassengerService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string InsertPassengerDetails(BusServicesClient.ServiceReference1.Passenger passeInfo) {
            return base.Channel.InsertPassengerDetails(passeInfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertPassengerDetailsAsync(BusServicesClient.ServiceReference1.Passenger passeInfo) {
            return base.Channel.InsertPassengerDetailsAsync(passeInfo);
        }
        
        public System.Data.DataSet GetAllPassengerDetails() {
            return base.Channel.GetAllPassengerDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllPassengerDetailsAsync() {
            return base.Channel.GetAllPassengerDetailsAsync();
        }
        
        public bool DeletePassengerDetails(int Id) {
            return base.Channel.DeletePassengerDetails(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePassengerDetailsAsync(int Id) {
            return base.Channel.DeletePassengerDetailsAsync(Id);
        }
        
        public string UpdatePassengerDetails(BusServicesClient.ServiceReference1.Passenger passInfo) {
            return base.Channel.UpdatePassengerDetails(passInfo);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePassengerDetailsAsync(BusServicesClient.ServiceReference1.Passenger passInfo) {
            return base.Channel.UpdatePassengerDetailsAsync(passInfo);
        }
        
        public System.Data.DataSet GetPassengerByName(string passInfoName) {
            return base.Channel.GetPassengerByName(passInfoName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPassengerByNameAsync(string passInfoName) {
            return base.Channel.GetPassengerByNameAsync(passInfoName);
        }
    }
}
